### ISSUE TITLE
encode special char in cookie value

### ISSUE THREAD

**Issue by bill2004158** [errai/errai#134]
Read the javadoc once again (emphasis mine):

> With Version 0 cookies, values should not contain white space, brackets, parentheses, equals signs, commas, double quotes, slashes, question marks, at signs, colons, and semicolons. Empty values may not behave the same way on all browsers.

however, it seems this method:
[UserCookieEncoder.toCookieValue()](https://github.com/errai/errai/blob/master/errai-security/errai-security-server/src/main/java/org/jboss/errai/security/shared/api/UserCookieEncoder.java#L45)

it doesn't encode those special char for cookie vlaue!

because of those invliad vlaue, wildfly cannot parse the correct value, even parse fail.

**Comment by mbarkley** [comment]
Closing as Errai security no longer uses a cookie.
