### ISSUE TITLE
Polymer elements are initialized twice

### ISSUE THREAD

**Issue by suneelv** [errai/errai#151]
When I tried to use a custom polymer element in errai GWT application, the element is initialized twice. 
cloneWithEmptyParent method in TemplateUtil.java i think is the culprit. Since I already have the element in template, when it is stamped, custom element is initialized. But because of the deep cloning in the cloneWithEmptyParent method, i think the element is initialized again. Please help to fix it

**Comment by mbarkley** [comment]
Closing this as the Errai Tutorial now demonstrates how to use a Polymer element in a @Templated bean: https://github.com/errai/errai-tutorial/blob/master/src/main/java/org/jboss/errai/demo/client/local/ContactEditor.java#L71
