### ISSUE TITLE
Errai i18n can't have a global key 

### ISSUE THREAD

**Issue by kevzlou7979** [errai/errai#172]
Hi Errai Team,

How can we have a global key value pair inside the json file on Errai that will work both
WelcomePage.html and LoginPage.html

e.g.
### Inside i18n.json

``` json
{
   "hello" : "hello"
}
```
### This is the current implementation based on errai i18n docs

We dont want to declare two instances of Hello because if we have 10 pages that require hello
  then we will define "page.key" : "value" so it will be very very long

``` json
{
  "WelcomePage.hello" : "hello",
  "LoginPage.hello" : "hello"
}
```
### Inside WelcomePage.html

``` html
<p data-i18n-key="hello"></hello>
```
### Inside LoginPage.html

``` html
<p data-i18n-key="hello"></hello>
```

**Comment by kevzlou7979** [comment]
Any news Errai Team??

**Comment by mbarkley** [comment]
HI,

Currently there is not a way to define a translation key for multiple templates with one declaration. If you find that you have the same value being translated in many templates, you could extract that to it's own template and use it as a data-field.

For example you could make a `@Templated` bean like this (this example uses non-composite templated beans supported only in Errai 4):

###### HelloDiv.java
    @Templated
    public class HelloDiv {
      @Inject @DataField
      private Div hello;
    }

##### HelloDiv.html
    <div data-field="hello" data-i18n-key="hello"></div>

Then in any templated bean where you have a "hello" data field you can add this field, allowing you to only provide the translation for the key "HelloDiv.hello":

    @Inject @DataField private HelloDiv hello;

**Comment by mbarkley** [comment]
This is now supported: https://issues.jboss.org/browse/ERRAI-993
