### ISSUE TITLE
Errai i18n : Support multiple Versions of the same language

### ISSUE THREAD

**Issue by kevzlou7979** [errai/errai#173]
One question is can we have multiple versions of the same language or provide the translation from the server
For example, we have multiple English clients that use your system, however they have a different way of referring to certain fields
So currently we set localization for each client, and their localization extends an existing default localization pack
So we use the default values, unless it is extended by their implementation

**Comment by kevzlou7979** [comment]
Any news Errai Team??

**Comment by mbarkley** [comment]
Hi,

We currently don't have support for loading translation bundles from the server at runtime. If that's a requirement of yours, you might consider translating your templates on the server with another i18n tool and then using a [template provider](http://docs.jboss.org/errai/latest/errai/reference/html_single/#_template_providers).
