### ISSUE TITLE
Forge Shell : Failed to install Errai 4.0.0.Beta1

### ISSUE THREAD

**Issue by kevzlou7979** [errai/errai#174]
Hi Errai Team,

We are trying to create a fresh Errai 4.0.0.Beta1 but we get an error.
![image](https://cloud.githubusercontent.com/assets/3138071/15806896/27a1a020-2b81-11e6-87ef-5da3561cad72.png)

Best Regards,
Kevin

**Comment by mbarkley** [comment]
Hi,

I think this is related to an issue I recently fixed on master. We were using an old URL for the DTD in the generated *.gwt.xml file, and that URL is now dead which causes errors in the XML parser.

This problem should go away if you use the 4.0.0-SNAPSHOT Forge addon.

**Comment by kevzlou7979** [comment]
Is 4.0.0-SNAPSHOT available, thanks :)

**Comment by mbarkley** [comment]
We are disabling GitHub issues for this project in favour of issue tracking through [JIRA](https://issues.jboss.org/projects/ERRAI).

If this problem still exists for the current Errai 4 release (4.0.0.CR3) please reopen the issue in JIRA.
