### ISSUE TITLE
Errai - Widget onLoad() called twice

### ISSUE THREAD

**Issue by kevzlou7979** [errai/errai#185]
Hi Errai Team,

Im using Errai 4.0.0.Beta1 for gwt-material, and it seems that the Widget onLoad() method called twice in errai.

Here is the sample widget that we implement the onload process
https://github.com/GwtMaterialDesign/gwt-material-addins/blob/master/src/main/java/gwt/material/design/addins/client/richeditor/MaterialRichEditor.java

And here is the Injection declaration of the widget

``` java
    @Inject
    @DataField
    MaterialRichEditor rich;
```

**Comment by kevzlou7979** [comment]
Here is our issue on gwt-material-addins https://github.com/GwtMaterialDesign/gwt-material-demo-errai/issues/1

**Comment by mbarkley** [comment]
Hi @kevzlou7979,

Would you mind opening a [JIRA](https://issues.jboss.org/projects/ERRAI/summary) issue for this? We don't use GitHub for issue tracking so this is less likely to get lost if you file a JIRA issue.

Cheers.
