### ISSUE TITLE
navigateBackOrToPage cleans page state

### ISSUE THREAD

**Issue by abmancini** [errai/errai#188]
if I understand correctly the implementation of navigateBackOrToPage 

@Override
  public void navigateBackOrToPage(final Class<?> pageType) {
    if (lastPageCache != null) {
      navigation.goTo(lastPageCache, ImmutableMultimap.<String, String>of());
      lastPageCache = null;
    }
    else {
      navigation.goTo(pageType, ImmutableListMultimap.<String, String>of());
    }
  }

page state is emptied during redirection.
Can you suggest any approach to keep the page state ?

**Comment by mbarkley** [comment]
Hi @abmancini,

This looks like a bug in the implementation. We really ought to cache the page state as well.

If you care to open a [JIRA issue](https://issues.jboss.org/projects/ERRAI), we could schedule a fix for our next release.

Cheers.

**Comment by abmancini** [comment]
Hi @mbarkley,
thank you very much, done. 

JIRA issue: https://issues.jboss.org/browse/ERRAI-982
