### ISSUE TITLE
Errai SDM - Code refresh doesnt compile HTML Files 

### ISSUE THREAD

**Issue by kevzlou7979** [errai/errai#197]
Hi Errai Team,

Errai Version: 4.0.0-Beta3
GWT Version: 2.8.0

When running Super Dev Mode, and I changed something inside .html file and refresh the browser. It seems that Errai does not update my code changes. If I changed both .html and .java for example it's working back.

Best Regards,
Kevin

**Comment by mbarkley** [comment]
Hi @kevzlou7979,

I've just verified that this works with our [tutorial](https://github.com/errai/errai-tutorial), so I am closing this issue.

I'd suggest comparing your configuration to our tutorial, or asking for help on our forum.

If you would like to file a bug report, please do so through [JIRA](https://issues.jboss.org/projects/ERRAI). That being said we will need more details (ideally a reproducer) to be able to act on it.

Cheers.
