### ISSUE TITLE
End Tag Issue on HTML Template

### ISSUE THREAD

**Issue by kevzlou7979** [errai/errai#198]
Hi Errai Team,

Errai Version: 4.0-Beta3
GWT Version: 2.8.0

I found some issue inside the html template , end tags like ``` <div /> ``` is not working. 
It will be better to support this one.

Best Regards,
Kevin

**Comment by mbarkley** [comment]
Hi @kevzlou7979,

I'm closing this because it is not an Errai issue. In HTML5, `<div />` is malformed because you cannot arbitrarily self-close tags. You can read about that [here](http://stackoverflow.com/questions/3558119/are-self-closing-tags-valid-in-html5).

Cheers.
