### ISSUE TITLE
IsElement doesn't supply a default method for getElement()

### ISSUE THREAD

**Issue by smoyer64** [errai/errai#200]
In the Errai UI section of the manual (https://github.com/errai/errai/blob/master/errai-docs/src/main/asciidoc/reference.asciidoc#implement-orgjbosserraiuiclientlocalapiiselement), it's stated that IsElement provides a default implementation of getElement() but there's no default method in the code.  This section also describes the IsElement interface as being in two different packages.

**Comment by mbarkley** [comment]
Hi Steve,

Perhaps this is not clear from the documentation but there are 2 IsElement interfaces. The one in errai-common does not have a default implementation. The one in errai-ui extends the the former and it does have a default implementation.

Cheers.

**Comment by smoyer64** [comment]
Ouch! ... I created a View interface with a few other methods I want all my components to include, so when I imported the IsElement I extended my interface from, I caused the problem for all my views!

Thanks for the pointer!
