### ISSUE TITLE
old devmode support

### ISSUE THREAD

**Issue by slavap** [errai/errai#205]
Not sure if it's issue or as design. I've updated my project to Errai 4.0 Beta4, and now old devmode cannot even start, fails with:
Unable to load module entry point class org.jboss.errai.marshalling.client.api.MarshallerFramework
com.google.gwt.core.client.JavaScriptException: (null) @org.jboss.errai.common.client.logging.util.Console::info(Ljava/lang/String;)([string: '23:24:29 INFO [InitVotes] wait for: org.jboss.errai.marshalling.client.api.MarshallerFramework']): null

I see that it fails in ErraiConsoleLogHandler on the following line:
logWith(msg, record, m -> Console.info(m));

Probably because Console is native JsType now.
Superdev mode works without any problems.
So my question is: is it a bug or expected behavior(devmode completely deprecated) ?

I've tried -generateJsInteropExports compiler's option, but no difference.

**Comment by aofner** [comment]
Hi @slavap. Errai 4.0 Beta4 added a dependency to Guava Release 20.0.
 
They mentioned "**Additionally, Guava 20.0 no longer works with the deprecated GWT "classic" Dev Mode.** It continues to work with Super Dev Mode" in their release notes:
[https://github.com/google/guava/wiki/Release20](https://github.com/google/guava/wiki/Release20) -> GWT notes

**Comment by slavap** [comment]
Not sure that's the case, I've updated Guava to version 20 few weeks ago, and "old devmode" was working just fine.

**Comment by slavap** [comment]
May be JsType for Console is declared incorrectly? Here I see "<window>", not "window"
https://github.com/gwtproject/gwt/blob/1ac4435e68ee75e47fa8eb58095fedc53c58462e/user/super/com/google/gwt/emul/javaemul/internal/NativeRegExp.java

**Comment by mbarkley** [comment]
Hi @slavap,

This is expected behaviour. We are attempting to move away from use of JSNI (though this is a slow process), and as such we can no longer support classic dev mode.

Cheers.
