### ISSUE TITLE
BindableProxyAgent.oneTypeIsInterface() is implemented incorrectly

### ISSUE THREAD

**Issue by slavap** [errai/errai#210]
```java
private boolean oneTypeIsInterface(final Class<?> propertyType, final Class<?> converterModelType) {
    return propertyType.isInterface() ^ converterModelType.isInterface();
}
```
XOR should be replaced by OR, because if both types are interfaces this method currently returns false, but must return true. The real meaning of this method is: at least one of two types is interface.

**Comment by mbarkley** [comment]
Hi @slavap,

Can you demonstrate a scenario in which this causes a problem for you? As far as I can tell, `propertyType` is always the type of a property in a `@Bindable` class, making it always either a concrete class or else `List`. And in the case of a `List` property, I'm not sure this even gets called.

Cheers.

**Comment by slavap** [comment]
First of all, current code is just illogical :-)
Yes, currently in model it could be only List.
But I have few converters, which are used not only in Errai related code, but in other places as well. Of course I can make an additional classes for Errai only, but it's just boring. 
Simplest example:
```java
    /** Allows binding to collection's size. */
    public static class SizeConverter implements Converter<Collection<?>, String> {

        public SizeConverter() {
        }

        @Override
        public Collection<?> toModelValue(String widgetValue) {
            throw new UnsupportedOperationException("SizeConverter is one-way only");
        }

        @Override
        public String toWidgetValue(Collection<?> modelValue) {
            return Empty.is(modelValue) ? "0" : String.valueOf(modelValue.size());
        }

        @SuppressWarnings({ "unchecked", "rawtypes" })
        @Override
        public Class<Collection<?>> getModelType() {
            Class<Collection<?>> rslt = (Class) Collection.class;
            return rslt;
        }

        @Override
        public Class<String> getComponentType() {
            return String.class;
        }
    }
```

**Comment by slavap** [comment]
@mbarkley Any updates on this issue?

**Comment by mbarkley** [comment]
Hi @slavap,

No progress on this yet. You can help resolve this more quickly by creating a [JIRA issue](https://issues.jboss.org/projects/ERRAI) (we don't use GitHub for issue tracking).

Cheers.
