### ISSUE TITLE
Using JPA and Validation requires class files

### ISSUE THREAD

**Issue by chvndb** [errai/errai#237]
I am testing Errai 4 together with Gradle, see:

https://github.com/chvndb/errai-gradle-demo.

I am trying to use client-side JPA. However, Errai only generates the correct `ErraiEntityManagerFactory` when I include the compiled class files to the classpath when running the GWT compiler.

Otherwise, the `GeneratedErraiEntityManagerFactory` is empty and I get runtime errors saying that the Named queries do not exist.

As a sanity check, is this the intended behaviour? As I was always under the impression that Errai did not need the compiled classes.

**Comment by mbarkley** [comment]
Hi @chvndb,

This behaviour is intentional. To avoid having to query the type oracle repeatedly to find all types with particular annotations, Errai uses a fork of Reflections to scan for classes with particular annotations. Hence the requirement to have compiled class files.

**Comment by chvndb** [comment]
I see, good to know. Maybe we can add this information to the documentation somewhere?

**Comment by mbarkley** [comment]
We are disabling GitHub issues for this project in favour of issue tracking through [JIRA](https://issues.jboss.org/projects/ERRAI).

I have created an issue to update the documentation, [here](https://issues.jboss.org/browse/ERRAI-1047).
