### ISSUE TITLE
Multiple active @Sync will always spawn an IllegalStateException

### ISSUE THREAD

**Issue by chvndb** [errai/errai#240]
Testing with `Errai4.0.0.CR1`.

When using client side JPA together with server side data sync, it is not possible to use multiple active @Sync methods.

If I go through the code, I see that `ClientSyncWorker` uses `ClientSyncManager.getInstance()`. The problem is that `ClientSyncManager` does not allow multiple synchronisations because of the `syncInProgress` logic.

Is there a reason it was designed like this? Thread safety?

Does this mean that we should never have more than one @Sync operation active at all times?

**Comment by mbarkley** [comment]
Hi @chvndb,

This behaviour seems like a bug. Please consider opening a [JIRA issue](https://jira.jboss.org/projects/ERRAI/issues/) for this (we don't use GitHub for issue tracking), or perhaps a pull request if you're feeling ambitious.

Cheers.

**Comment by chvndb** [comment]
Ok, will do when I get the time as I also noticed that defining multiple @Sync on one bean gives code generation issues. Duplicate local variables are defined in the generated Type_factory.

**Comment by chvndb** [comment]
I also noticed strange behaviour for server/client data sync for entities referencing other entities. 

E.g. albums made by artists. When I want to retrieve all the albums made by a specific artist, this works fine for the client-side JPA implementation.

However, the ClientSyncManager has issues with this. I dug a little and noticed that the expected entity manager from the ClientSyncManager fails to retrieve this relation correctly and will always think the albums are new entities for the specified user. Therefore, the ClientSyncManager syncs this to the server and the next sync, the same happens. This ends in an endless addition of albums.

Again, I am parking the issue here as I do not have time to create a detailed issue in the Errai issue tracker. Will do so when I get the time.

**Comment by mbarkley** [comment]
We are disabling GitHub issues for this project in favour of issue tracking through [JIRA](https://issues.jboss.org/projects/ERRAI).

I have copied your initial description of the problem to this [issue](https://issues.jboss.org/browse/ERRAI-1048). Cheers.
