### ISSUE TITLE
Migrate from mojo to tbroyer gwt plugin.

### ISSUE THREAD

**Issue by kevzlou7979** [errai/errai#252]
Hi Errai Team,

Are you planning to migrate mojo to tbroyer gwt-maven-plugin.
Here's the reference .

https://github.com/tbroyer/gwt-maven-plugin

Best Regards,
Kevin

**Comment by ge0ffrey** [comment]
The mojo gwt plugin guys clearly state that the tbroyer gwt plugin replaces it, so sooner or later errai will want to move (but maybe not before uberfire, appformer and kie do).

That being said, there's no problem today to consume errai from tbroyer gwt plugin based projects (see optashift-employee-rostering).

**Comment by mbarkley** [comment]
Yes, we will have to update to the new plugin eventually. I just haven't prioritised it yet.

@kevzlou7979 I am closing this issue because you have already created a JIRA issue (and thanks for doing so :) ).
