### ISSUE TITLE
Support META-INF/ErraiApp.properties too

### ISSUE THREAD

**Issue by ge0ffrey** [errai/errai#255]
According to Java guidelines, all files in a jar must be namespaced by a unique package, except for the jar specific files in the META-INF directory.

- `/ErraiApp.properties` violates this policy

Examples of projects that respect that policy:

- `/META-INF/persistence.xml` JPA/Hibernate
- `/META-INF/kmodule.xml` Drools/OptaPlanner/jBPM
- `/META-INF/beans.xml` CDI/Weld

Proposed solution:

**Support the use of `/META-INF/ErraiApp.properties` too and change all documentation and examples to put it there.** Do keep allowing the use of `/ErraiApp.properties` as a fallback for backwards compatibility reasons.

**Comment by mbarkley** [comment]
Hi @ge0ffrey,

Closing this issue as I have copied it [here](https://issues.jboss.org/browse/ERRAI-1042) to the project JIRA.

**Comment by ge0ffrey** [comment]
@mbarkley note that it's possible in the git repo settings to disable the issues tab here.
Do note that I didn't see the jira link on the errai website, so I wouldn't have found it potentially...

**Comment by mbarkley** [comment]
@ge0ffrey Yeah, I hadn't found how to disable issues the last time I looked, but I see it today and intend to close all open issues and disable it for the project.

The JIRA is linked from the project website, albeit at the bottom of the page in dark font. Maybe something to look at changing in the future.
