### ISSUE TITLE
Getting started broken: Do not depend on xercesImpl 2.11.0.SP4 because that doesn't exist in Maven Central

### ISSUE THREAD

**Issue by ge0ffrey** [errai/errai#256]
Try building a hello world project with Errai without explicitly adding the Jboss maven repository in the pom or in your settings.xml.

You'll run into:
   [ERROR] ...Could not resolve dependencies for project ...T: Failure to find xerces:xercesImpl:jar:2.11.0.SP4
for example after adding the artifact errai-javaee-all.

2.11.0.SP4 is in Jboss nexus:
  https://repository.jboss.org/nexus/content/groups/public/xerces/xercesImpl/2.11.0.SP4/
but it isn't synced to maven central:
  http://mvnrepository.com/artifact/xerces/xercesImpl

Do "mvn dependency:tree -Dverbose" on errai-javaee-all and clean up the dependency tree.

**Comment by ge0ffrey** [comment]
Ok, this is more complex, let me explain what happens.

Here's the output of "mvn dependency:tree -Dverbose" with the jboss repo included in the pom.xml:

```
org.optaplanner.openshift:optashift-employee-rostering-gwtui:gwt-app:0.1.0-SNAPSHOT
+- com.google.gwt:gwt-dev:jar:2.8.0:compile
|  +- net.sourceforge.htmlunit:htmlunit:jar:2.19:compile
|  |  +- xerces:xercesImpl:jar:2.11.0.SP4:compile (version managed from 2.11.0)
\- org.jboss.errai:errai-javaee-all:jar:4.0.0.CR3:compile
```

1) gwt-dev pulls in xercesImpl indirectly
2) errai upgrades it from 2.11.0 to 2.11.0.SP4. Notice the _version managed from ..._ in the snippet above
3) crash because 2.11.0.SP4 is not in Maven Central

**Comment by ge0ffrey** [comment]
Not sure how to fix this though, as xercesImpl SP4 means it fixes things (security probably) in xercesImpl 2.11.0 and there is no newer version on Central. Xerces is dead - ideally gwt-dev should stop depending on it... I doubt errai even uses it.

Meanwhile, this breaks the getting started experience of Errai, so a fix is needed. Idea's to investigate (@psiroky I think we need you :)):
- remove xerces version from the ip-bom and exclude it everywhere.
- overwrite xerces version in errai-parent
- create an issue with gwt-dev and push them to fix it asap
- pom dependency exclusion elements on gwt-dev?

**Comment by ge0ffrey** [comment]
**Workaround for users** (it should be fixed in errai itself)
Add this dependency:
```
      <dependency>
        <!-- TODO remove me, workaround for https://github.com/errai/errai/issues/256 -->
        <groupId>xerces</groupId>
        <artifactId>xercesImpl</artifactId>
        <version>2.11.0</version>
      </dependency>
```

**Comment by mbarkley** [comment]
Hi @ge0ffrey,

Closing this as I've copied the issue to [JIRA](https://issues.jboss.org/browse/ERRAI-1043).
