### ISSUE TITLE
Getting started broken on errai-ui: Unable to find 'org/jboss/errai/databinding/DataBinding.gwt.xml' on your classpath

### ISSUE THREAD

**Issue by ge0ffrey** [errai/errai#258]
I only need to use errai-ui for now, so I followed the instructions on this page:
  http://erraiframework.org/getting-started/index.html#ErraiUIPage
and added the dependency and inherited module, which causes:

```
[INFO] --- gwt-maven-plugin:1.0-rc-6:compile (default-compile) @ optashift-employee-rostering-gwtui ---
[INFO] Loading inherited module 'org.optaplanner.openshift.employeerostering.gwtui.WorkerRosteringWebapp'
[INFO]    Loading inherited module 'org.jboss.errai.ui.UI'
[INFO]       Loading inherited module 'org.jboss.errai.databinding.DataBinding'
[INFO]          [ERROR] Unable to find 'org/jboss/errai/databinding/DataBinding.gwt.xml' on your classpath; could be a typo, or maybe you forgot to include a classpath entry for source?
```

**Comment by ge0ffrey** [comment]
**Workaround**: add this dependency:

```
    <dependency>
      <groupId>org.jboss.errai</groupId>
      <artifactId>errai-data-binding</artifactId>
    </dependency>
```

Looks like errai-ui is missing a transitive non-optional dependency on errai-data-binding.

**Comment by ge0ffrey** [comment]
I've submitted a PR for this: https://github.com/errai/errai/pull/259

Also, looks like that all usages of `<scope>provided</scope>` in dependency elements should be replaced by `<optional>true</optional>`.

**Comment by mbarkley** [comment]
Hi @ge0ffrey,

Closing this issue as I've copied it to [JIRA](https://issues.jboss.org/browse/ERRAI-1045).
